name: জীবনানন্দ দাশের কবিতাসমগ্র
title: জীবনানন্দ দাশের কবিতাসমগ্র
url: https://জীবনানন্দ.বাংলা
baseurl: https://জীবনানন্দ.বাংলা
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

 plugins:
  - jekyll-sitemap
