name: জীবনানন্দ দাশের কবিতাসমগ্র
title: জীবনানন্দ দাশের কবিতাসমগ্র
description:
url: https://jibanananda.ml
baseurl: 
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
